=== Morisummer135/CDOJ/trunk/src/main/resources/cdoj-settings.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!--
          ~ /*
          ~  * cdoj, UESTC ACMICPC Online Judge
          ~  * Copyright (c) 2013 fish <@link lyhypacm@gmail.com>,
          ~  * 	mzry1992 <@link muziriyun@gmail.com>
          ~  *
          ~  * This program is free software; you can redistribute it and/or
          ~  * modify it under the terms of the GNU General Public License
          ~  * as published by the Free Software Foundation; either version 2
          ~  * of the License, or (at your option) any later version.
          ~  *
          ~  * This program is distributed in the hope that it will be useful,
          ~  * but WITHOUT ANY WARRANTY; without even the implied warranty of
          ~  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
          ~  * GNU General Public License for more details.
          ~  *
          ~  * You should have received a copy of the GNU General Public License
          ~  * along with this program; if not, write to the Free Software
          ~  * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
          ~  */
          -->

        <!-- START SNIPPET: settingsDtd -->

        <!--
           UESTC Online Judge Settings configuration DTD.
           Use the following DOCTYPE

           <!DOCTYPE cdoj-settings SYSTEM "cdoj-settings.dtd">
        -->
        <!ELEMENT cdoj-settings (setting)*>
        <!ELEMENT setting (item|list)*>
        <!ATTLIST setting
                name CDATA #REQUIRED
                >

        <!ELEMENT list (item)*>
        <!ATTLIST list
                name CDATA #REQUIRED
                description CDATA #REQUIRED
                >

        <!ELEMENT item (#PCDATA|prop)*>
        <!ATTLIST item
                name CDATA #REQUIRED
                description CDATA #REQUIRED
                >
        <!ELEMENT prop (#PCDATA)>
        <!ATTLIST prop
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

=== Morisummer135/CDOJ/trunk/src/main/resources/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ /*
  ~  * cdoj, UESTC ACMICPC Online Judge
  ~  * Copyright (c) 2013 fish <@link lyhypacm@gmail.com>,
  ~  * 	mzry1992 <@link muziriyun@gmail.com>
  ~  *
  ~  * This program is free software; you can redistribute it and/or
  ~  * modify it under the terms of the GNU General Public License
  ~  * as published by the Free Software Foundation; either version 2
  ~  * of the License, or (at your option) any later version.
  ~  *
  ~  * This program is distributed in the hope that it will be useful,
  ~  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~  * GNU General Public License for more details.
  ~  *
  ~  * You should have received a copy of the GNU General Public License
  ~  * along with this program; if not, write to the Free Software
  ~  * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
  ~  */
  -->
<!DOCTYPE cdoj-settings SYSTEM "cdoj-settings.dtd">
<cdoj-settings>
    <setting name="setting">
        <item name="encoding" description="default encoding">UTF-8</item>
        <item name="uploadSize" description="upload file size(in MB)">100</item>
        <item name="uploadTypes" description="upload file's types">
            in;out;jpg;jpeg;png;gif;doc;docx;xls;xlsx;ppt;pptx;pdf;rar;zip;
        </item>
        <item name="uploadFolder" description="upload files store folder">/uploads/</item>
        <item name="problemPictureFolder" description="problems' pictures store folder">/images/problem/</item>
    </setting>
    <setting name="judge">
        <item name="judgeCore" description="judge core name">pyloncore</item>
        <item name="dataPath" description="data path name">/WEB-INF/data/</item>
        <item name="tempPath" description="work path name">/WEB-INF/work/</item>
        <list name="judges" description="judge list">
            <item name="judge" description="judge item">
                <prop name="name" value="fish"/>
            </item>
            <item name="judge" description="judge item">
                <prop name="name" value="mzry1992"/>
            </item>
        </list>
    </setting>
    <setting name="email">
        <item name="address" description="sender address">cdoj_test@163.com</item>
        <item name="username" description="sender email user name">cdoj_test@163.com</item>
        <item name="password" description="sender email password">135678942570</item>
        <item name="smtpServer" description="smtp server address">smtp.163.com</item>
    </setting>
</cdoj-settings>
